"""
data/clean_pipeline.py

Loads raw CSVs generated by generate_data.py, runs validation and cleaning,
then writes clean_*.csv files ready for SQLite ingestion.

Run from project root:
    python data/clean_pipeline.py

Output:
    data/clean_campaigns.csv
    data/clean_physician_offices.csv
    data/clean_campaign_placements.csv
    data/clean_daily_metrics.csv
    data/clean_weekly_benchmarks.csv
    + printed validation report
"""

import os
import sys
import numpy as np
import pandas as pd

DATA_DIR = os.path.dirname(os.path.abspath(__file__))


# ── Helpers ────────────────────────────────────────────────────────────────────
def load(filename: str) -> pd.DataFrame:
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        print(f"  ERROR: {filename} not found. Run generate_data.py first.")
        sys.exit(1)
    return pd.read_csv(path)


def section(title: str):
    print(f"\n{'─' * 50}")
    print(f"  {title}")
    print(f"{'─' * 50}")


def null_report(df: pd.DataFrame, name: str):
    null_counts = df.isnull().sum()
    has_nulls = null_counts[null_counts > 0]
    if has_nulls.empty:
        print(f"  ✓ {name}: no nulls")
    else:
        print(f"  ✗ {name}: nulls found →")
        for col, cnt in has_nulls.items():
            pct = cnt / len(df) * 100
            print(f"      {col}: {cnt:,} ({pct:.1f}%)")
    return has_nulls


def dedup_report(df: pd.DataFrame, id_col: str, name: str) -> pd.DataFrame:
    before = len(df)
    df = df.drop_duplicates(subset=[id_col])
    after = len(df)
    dropped = before - after
    status = "✓" if dropped == 0 else "⚠"
    print(f"  {status} {name}: {before:,} rows → {after:,} after dedup on {id_col} ({dropped} dropped)")
    return df


def range_check(df: pd.DataFrame, col: str, lo: float, hi: float, name: str) -> pd.DataFrame:
    out_of_range = ((df[col] < lo) | (df[col] > hi)).sum()
    if out_of_range == 0:
        print(f"  ✓ {name}.{col}: all values in [{lo}, {hi}]")
    else:
        print(f"  ⚠ {name}.{col}: {out_of_range:,} values outside [{lo}, {hi}] — clipping")
        df[col] = df[col].clip(lo, hi)
    return df


# ── Per-table cleaning ─────────────────────────────────────────────────────────
def clean_campaigns(df: pd.DataFrame) -> pd.DataFrame:
    # Types
    df["start_date"] = pd.to_datetime(df["start_date"]).dt.date.astype(str)
    df["end_date"]   = pd.to_datetime(df["end_date"]).dt.date.astype(str)
    df["budget"]     = pd.to_numeric(df["budget"], errors="coerce")
    df["target_completion"] = pd.to_numeric(df["target_completion"], errors="coerce")
    df["is_ab_demo"] = df["is_ab_demo"].astype(int)

    # Nulls + dedup
    null_report(df, "campaigns")
    df = dedup_report(df, "campaign_id", "campaigns")

    # Range checks
    df = range_check(df, "target_completion", 0.0, 1.0, "campaigns")
    df = range_check(df, "budget", 0, 10_000_000, "campaigns")

    # Verify start < end
    bad_dates = (df["start_date"] >= df["end_date"]).sum()
    print(f"  {'✓' if bad_dates == 0 else '✗'} campaigns: {bad_dates} rows with start_date >= end_date")

    return df


def clean_offices(df: pd.DataFrame) -> pd.DataFrame:
    null_report(df, "physician_offices")
    df = dedup_report(df, "office_id", "physician_offices")

    # Validate tier values
    valid_tiers = {"A", "B", "C"}
    bad_tiers = (~df["tier"].isin(valid_tiers)).sum()
    print(f"  {'✓' if bad_tiers == 0 else '✗'} physician_offices: {bad_tiers} invalid tier values")

    # Validate region values
    valid_regions = {"Northeast", "Midwest", "South", "West"}
    bad_regions = (~df["region"].isin(valid_regions)).sum()
    print(f"  {'✓' if bad_regions == 0 else '✗'} physician_offices: {bad_regions} invalid region values")

    return df


def clean_placements(df: pd.DataFrame) -> pd.DataFrame:
    null_report(df, "campaign_placements")
    df = dedup_report(df, "placement_id", "campaign_placements")

    valid_screens = {"waiting_room", "exam_room"}
    bad_screens = (~df["screen_type"].isin(valid_screens)).sum()
    print(f"  {'✓' if bad_screens == 0 else '✗'} campaign_placements: {bad_screens} invalid screen_type values")

    return df


def clean_metrics(df: pd.DataFrame) -> pd.DataFrame:
    # Types
    df["date"]            = pd.to_datetime(df["date"]).dt.date.astype(str)
    df["impressions"]     = pd.to_numeric(df["impressions"], errors="coerce").fillna(0).astype(int)
    df["completions"]     = pd.to_numeric(df["completions"], errors="coerce").fillna(0).astype(int)
    df["skips"]           = pd.to_numeric(df["skips"],       errors="coerce").fillna(0).astype(int)
    df["ctr"]             = pd.to_numeric(df["ctr"],             errors="coerce").fillna(0.0)
    df["completion_rate"] = pd.to_numeric(df["completion_rate"], errors="coerce").fillna(0.0)

    null_report(df, "daily_metrics")
    df = dedup_report(df, "metric_id", "daily_metrics")

    # Range checks
    df = range_check(df, "completion_rate", 0.0, 1.0, "daily_metrics")
    df = range_check(df, "ctr",             0.0, 1.0, "daily_metrics")

    # Logical check: completions <= impressions
    bad_completions = (df["completions"] > df["impressions"]).sum()
    if bad_completions > 0:
        print(f"  ⚠ daily_metrics: {bad_completions:,} rows where completions > impressions — fixing")
        df.loc[df["completions"] > df["impressions"], "completions"] = df["impressions"]
    else:
        print(f"  ✓ daily_metrics: completions <= impressions on all rows")

    # Non-negative
    for col in ["impressions", "completions", "skips"]:
        neg = (df[col] < 0).sum()
        if neg > 0:
            print(f"  ⚠ daily_metrics: {neg} negative values in {col} — setting to 0")
            df[col] = df[col].clip(lower=0)

    return df


def clean_benchmarks(df: pd.DataFrame) -> pd.DataFrame:
    df["week_start"] = pd.to_datetime(df["week_start"]).dt.date.astype(str)
    df["week_end"]   = pd.to_datetime(df["week_end"]).dt.date.astype(str)
    df["target_completion_rate"] = pd.to_numeric(df["target_completion_rate"], errors="coerce")
    df["national_avg"]           = pd.to_numeric(df["national_avg"],           errors="coerce")

    null_report(df, "weekly_benchmarks")
    df = dedup_report(df, "benchmark_id", "weekly_benchmarks")
    df = range_check(df, "target_completion_rate", 0.0, 1.0, "weekly_benchmarks")
    df = range_check(df, "national_avg",           0.0, 1.0, "weekly_benchmarks")

    return df


# ── Summary stats ──────────────────────────────────────────────────────────────
def print_summary(tables: dict):
    section("CLEANING COMPLETE — Final row counts")
    for name, df in tables.items():
        print(f"  {name:<40} {len(df):>10,} rows")

    # Spot-check: date range on daily_metrics
    metrics = tables["clean_daily_metrics.csv"]
    print(f"\n  daily_metrics date range: {metrics['date'].min()}  →  {metrics['date'].max()}")

    # Spot-check: campaigns per region via placements+offices (can't join here, just offices)
    offices = tables["clean_physician_offices.csv"]
    region_counts = offices["region"].value_counts()
    print(f"\n  Offices by region:")
    for region, count in region_counts.items():
        print(f"    {region:<12} {count:>6,}")

    # Spot-check: completion rate distribution
    cr = metrics.loc[metrics["completion_rate"] > 0, "completion_rate"]
    print(f"\n  Completion rate (non-zero rows):")
    print(f"    mean={cr.mean():.4f}  std={cr.std():.4f}  min={cr.min():.4f}  max={cr.max():.4f}")


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    print("=" * 50)
    print("  PatientPoint — Cleaning Pipeline")
    print("=" * 50)

    section("Loading raw CSVs")
    raw = {
        "campaigns":           load("raw_campaigns.csv"),
        "physician_offices":   load("raw_physician_offices.csv"),
        "campaign_placements": load("raw_campaign_placements.csv"),
        "daily_metrics":       load("raw_daily_metrics.csv"),
        "weekly_benchmarks":   load("raw_weekly_benchmarks.csv"),
    }
    for name, df in raw.items():
        print(f"  Loaded {name}: {len(df):,} rows, {len(df.columns)} columns")

    section("Cleaning & validating")
    clean = {
        "clean_campaigns.csv":           clean_campaigns(raw["campaigns"]),
        "clean_physician_offices.csv":   clean_offices(raw["physician_offices"]),
        "clean_campaign_placements.csv": clean_placements(raw["campaign_placements"]),
        "clean_daily_metrics.csv":       clean_metrics(raw["daily_metrics"]),
        "clean_weekly_benchmarks.csv":   clean_benchmarks(raw["weekly_benchmarks"]),
    }

    section("Saving clean CSVs")
    for filename, df in clean.items():
        path = os.path.join(DATA_DIR, filename)
        df.to_csv(path, index=False)
        print(f"  Saved {filename}")

    print_summary(clean)
    print("\n  ✓ All clean. Run load_sqlite.py next.\n")


if __name__ == "__main__":
    main()
